# Define the goal
string expression       # Type of facial expression to be executed
float32 intensity        # Intensity of facial expression
float32 speed            # Speed of facial expression
float32 duration        # Duration the facial expression should be performed for
---
---
# Define a feedback message
