# Define the goal
string gesture              # Type of gesture to be executed
float32 duration            # Duration gesture for be performed for
string target   		    # The target to perform gesture toward
---
# Define the result
bool success
---
# Define a feedback message
float32 distance_to_target
