# This action definition is used for unit tests for multi goal action client
# Define the goal
float32 duration
---
# Define the result
bool success
---
# Define a feedback message
float32 current_time
